import type { Metadata } from "next";
import { Sekuya, Bebas_Neue } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";
import ScrollToHash from "./components/ScrollToHash";
import { Suspense } from "react";

const FontSekuya = Sekuya({
  variable: "--font-sekuya",
  weight: "400",
  subsets: ["latin"],
});

const FontBebasNeue = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mansoor Khan",
  description: "Generated by create next app",
  icons: ""
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${FontSekuya.variable} ${FontBebasNeue.variable} h-full antialiased`}>

      <body className="min-h-full flex flex-col relative overflow-x-hidden">
        <Suspense fallback={null}>
          <ScrollToHash />
        </Suspense>
        <CustomCursor />
        {/* Global Technical Grid & Noise Background */}
        <div className="fixed inset-0 -z-50 bg-background">
          <div
            className="absolute inset-0 opacity-20"
            style={{
              backgroundImage: `radial-gradient(var(--grid-color) 1px, transparent 1px)`,
              backgroundSize: `var(--grid-size) var(--grid-size)`
            }}
          />
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_80%_at_50%_0%,rgba(16,185,129,0.05),transparent)]" />
          <div
            className="absolute inset-0 opacity-[0.03] pointer-events-none"
            style={{
              backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`
            }}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
